services:
  db:
    image: postgres:18-alpine
    ports:
      - "5433:5432"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: test
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./apps/api/better-auth_migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "postgres"]
      interval: 3s

  mail:
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025" # expose SMTP to host
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:1080",
        ]
      interval: 3s

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_healthy
    environment:
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - DATABASE_URL=postgresql://testuser:testpass@db:5432/test
      - BETTER_AUTH_SECRET=uECOarRCMYJfTylXt2jo92JVTV6GbPjP
      - BETTER_AUTH_URL=http://localhost:3001
      - SMTP_HOST=mail
      - SMTP_PORT=1025

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:3001
