title: Admin Starter
description: Starter template for projects with user authentication and admin features.

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: solarized-dark
  nav_pages:
    - index.md

github_username: SubZtep
repository: SubZtep/admin-starter
