title: Admin Starter
description: Starter boilerplate for projects with user authentication and admin features.

plugins:
  - jekyll-remote-theme

remote_theme: pmarsceill/just-the-docs

color_scheme: dark
