title: Admin Starter
description: Starter boilerplate for projects with user authentication and admin features.
repository: SubZtep/admin-starter
permalink: pretty
heading_anchors: false

aux_links:
  "Source on GitHub":
    - "//github.com/SubZtep/admin-starter"
aux_links_new_tab: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

remote_theme: pmarsceill/just-the-docs

color_scheme: dark
favicon_ico: /images/favicon.ico
