name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Biome Toolchain
        uses: biomejs/setup-biome@v2
        with:
          version: "2.4.6"

      - name: Run linter and formatter
        run: biome ci .
